### ISSUE TITLE
Have a troubles in make step

### ISSUE THREAD

**Issue by sumskiya** [filcuc/QtCreatorNimEditor#5]
/nimplugin.cpp:56:48: error: parameter declarator cannot be qualified
    const QIcon icon (QLatin1String(Constants::C_NIM_ICON_PATH));
../nimplugin.cpp:57:14: error: member reference base type 'const QIcon (QLatin1String)' is not a structure or union
    if (!icon.isNull())
../nimplugin.cpp:58:9: error: no matching function for call to 'registerIconOverlayForMimeType'
        Core::FileIconProvider::registerIconOverlayForMimeType(icon, C_NIM_MIMETYPE);

OS X

**Comment by filcuc** [comment]
Can you try removing the "const" qualifier from the declaration of the QIcon at line 56?

**Comment by sumskiya** [comment]
Same error without "const":
1) ../nimplugin.cpp:56:42: error: parameter declarator cannot be qualified
    QIcon icon (QLatin1String(Constants::C_NIM_ICON_PATH));

2) ../nimplugin.cpp:57:14: error: member reference base type 'QIcon (QLatin1String)' is not a structure or union
    if (!icon.isNull())

3) ../nimplugin.cpp:58:9: error: no matching function for call to 'registerIconOverlayForMimeType'
        Core::FileIconProvider::registerIconOverlayForMimeType(icon, C_NIM_MIMETYPE);

**Comment by filcuc** [comment]
Which clang and Qt version are you using? Just for the sake of unblocking you, can you remove all those 3 lines that deal with the Icon?

**Comment by sumskiya** [comment]
Qt 5.5 , 

iMac-Anatoliy:build sumskiya$ qmake -v
QMake version 3.0
Using Qt version 5.5.0 in /Users/sumskiya/Applications/Qt/5.5/clang_64/lib

iMac-Anatoliy:build sumskiya$ clang -v
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.4.0
Thread model: posix

After deleting this 3 lines of code, still have 3 errors.

I think is a compiler wrong version.
Can u compile plugin for me?

**Comment by filcuc** [comment]
I'll try to bring up a VM with osx and build it there. However keep in mind that for now i've just tested and used this plugin on linux

**Comment by filcuc** [comment]
@sumskiya since June this plugin has been officially added to the QtCreator repo. You should find it in a recent built of QtCreator. You can google for "QtCreator snapshot" and test it by downloading a recent master build.
