### ISSUE TITLE
Supported Qt Creator version

### ISSUE THREAD

**Issue by RazrFalcon** [filcuc/QtCreatorNimEditor#6]
Which Qt Creator version is supported?
I tried to build Nim Plugin with 3.4.2 on Linux/gcc, but got tons of errors.

**Comment by filcuc** [comment]
Have you read the build instructions? i was able to build it this morning with the latest QtCreator branch
1) Grab the current QtCreator master branch e put yourself at commit abec43e7d32b5ded1b598e6f3accd8e389eb1db5 
2) Build QtCreator out of source 
3) Follow the instructions on my repo Readme

**Comment by RazrFalcon** [comment]
Thanks. With Qt Creator from git works.

**Comment by filcuc** [comment]
I'll close this as solved
