### ISSUE TITLE
Syntax highlighting missing

### ISSUE THREAD

**Issue by ghost** [filcuc/QtCreatorNimEditor#9]
Hi it seems there is no syntax highlighting for nim files, without it usability of this plugin lacks.

**Comment by filcuc** [comment]
Maybe you missed the warning on the project readme this has been already merged upstream in QtCreator. You Just Need to enable the Nim plugin in your ide. That said there is syntax highlighting in this repo

**Comment by filcuc** [comment]
See NimHighlighter.h

**Comment by filcuc** [comment]
i will close this one, feel free to reopen if you need more clarifications ;)

**Comment by ghost** [comment]
Thank you I found the checkbox. I thought that qtcreator used the same syntax highlighting files as kate/kdevelop hense the confusion.
